# Supabase project configuration
# https://supabase.com/docs/guides/cli/config

[api]
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
# URL of the site your application is hosted at
site_url = "exp://localhost:8081"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["exp://localhost:8081/--/auth/callback"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = false

[auth.email]
enable_signup = false
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false

[edge_runtime]
enabled = true

[analytics]
enabled = false
